/** @file SWC.C 
		  Generate C code  
*/

#include <stdio.h>
#include <stdlib.h>
#include "model.h"
#include "sw.h"

#define P(s) printf("// %s\n",(#s));
static void genSuffix() {

	P(wg.Wait());
	printf("}\n");
}

static void genPrefix(int nstreams) {

	printf("//  Prefix here. %d streams\n",nstreams);
	P(*		 	 DO NOT EDIT!!!
 *		generated by sw 
**/);

	printf("\t}\n\n");
}
	
static void genProcs(Process p) {	
    
	while(p) {
			printf("// (%s %s.%s) %d ports\n",
				p->name, 			
				p->comp->path,
				p->comp->name,
				p->nportsIn + p->nportsOut
			);
			p=p->next;
	}	
	
	printf("\n");
}	



void genC(Model model) {
	Stream f;
	Process p;
	
				//* Generate Prefix code */
	genPrefix(model->nstreams);
	
				
		//* Generate commented Reconstructed Network Definition */
	printf("/*********  Expanded Network Definition   ********/\n");
	f=model->stream;

	while(f) {
			printf("// (%s %s.%s)%d <- %d(%s %s.%s) \n", 
				f->sink->name,
				f->sink->comp->path,
				f->sink->comp->name,
				f->sink_id, 
				f->source_id, 
				f->source->name,
				f->source->comp->path,
				f->source->comp->name
			);
				
		f=f->next;
	}
	
	printf("\n");		 
	p=model->proc;  /* Get first process */
	genProcs(p); 
	genSuffix();	//* Generate Suffix code */
}

/*    End of SWC.C  */
