FROM golang:1.14

LABEL ""Streamwork Demo""
LABEL maintainer="streamwork@twyoung.com"
LABEL maintainer="streamwork@twyoung.com" 

# Needs to be in passwd file USER  tyoung3 tyoung3
WORKDIR /go/mod/sw
COPY  .  /go/mod/sw

ARG A_EDITOR="gedit"
ARG A_BROWSER="chrome"
ARG PKGS="apt-utils bnfc dialog $EDITOR gdb graphviz libyaml-dev locate texlive-binaries tree"
#  REMOVED: valgrind

ENV BROWSER=$A_BROWSER
ENV EDITOR="$A_EDITOR"
ENV APP_NAME="sw"
ENV MY_APP="Streamwork"

RUN apt-get -y update && apt-get -y upgrade && apt-get -y install  $PKGS
RUN mkdir /go/src/gen && ln -s /go /root/

RUN echo "deb http://ftp.us.debian.org/debian buster main" >>  /etc/apt/sources.list
RUN echo "set auto-load safe-path /" 		 >> 	/root/.gdbinit
RUN echo "Streamwork($APP_NAME).  Built: `date`" > 	/etc/motd 
RUN echo "export EDITOR=gedit"  		>> 	/root/.bashrc
RUN echo "export PATH=/go/mod/sw/bin:$PATH" 	>> 	/root/.bashrc
RUN echo "alias dir='ls -Fltr'"  		>> 	/root/.bashrc 
RUN echo "alias r='./run'"  			>> 	/root/.bashrc 


##################   The rest of this file is commentary.   ###################################

# ONBUILD <INSTRUCTION>
# STOPSIGNAL signal
# HEALTHCHECK [OPTIONS] CMD command

# Generated by run script.  DO NOT EDIT!
# see: http://docs.docker.com/engine/reference/builder/
## FAILED: ADD /home/tyoung3/go/src/gen/  /go/src/    
## ?? COPY  ./go/src  /go/src/gen   
## TODO: Set up www service.   Access xwindows from container. 
# Enable SSH:  No ssh server found in search
#RUN apt-cache search  sshd 
#RUN mkdir /var/run/sshd
#RUN echo 'root:JS86pb6QPEY' | chpasswd
#RUN sed -i 's/PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config

# SSH login fix. Otherwise user is kicked off after login
# Fails: RUN sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd

#ENV NOTVISIBLE "in users profile"
#RUN echo "export VISIBLE=now" >> /etc/profile

#EXPOSE 22
# CMD ["sw"] # Sets initial commandRUN apt-get update && apt-get install -y openssh-server


###  Docker Hub:   https://index.docker.io/   


	## Set EDITOR and BROWSER in docker image. 
	## Fix PATH.   ORIGINALLY: /go/bin:/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
	##   add /go/mod/sw/bin
	##   ln -s /go ~/go
	## Set hostname SWGEN 
	
	
#########################   End of Docker file   #################################
