site_name: StreamWork
nav:
  - Home: index.md
  - Readme: rdm.md
  - User Guide: 
      - Components: components.md
      - SwBase: components/sw.md 
      - Swutility: components/swutility.md
      - Linux:   components/linux.md
      - Config:  components/config.md
      - Fileio:  components/fileio.md 
  - Developer Guide: 
      - FBP:    FBP.md
      - Project Generation: PROJECT.md
      - Mkdocs: mkdocs.md   
      - Github Project: github.md 
      - Docker: DOCKER.md
  - About:    
      - License: license.md
      - About: about.md

copyright: Copyright &copy; 2022, Tom Young, streamwork@twyoung.com.

theme: readthedocs
