site_name: StreamWork
nav:
  - Home: index.md
  - SwHome: swhome.md
  - Readme: rdm.md
  - Github: github.md
  - License: license.md
  - Mkdocs: mkdocs.md
  - About: about.md
       
theme: readthedocs
