site_name: StreamWork
nav:
  - Home: index.md
  - Readme: rdm.md
  - Project: PROJECT.md
  - FBP:    FBP.md
  - Github: github.md
  - Docker: DOCKER.md
  - Mkdocs: mkdocs.md
  - License: license.md
  - About: about.md
       
theme: readthedocs
