site_name: StreamWork
nav:
  - Home: index.md
  - Readme: rdm.md
  - FBP:    FBP.md
  - Project: PROJECT.md
  - Github: github.md
  - Components: 
      - Component Comments: components.md
      - SwBase: components/sw.md 
      - Swutility: components/swutility.md
      - Linux:   components/linux.md
      - Config:  components/config.md
      - Fileio:  components/fileio.md 
  - Miscellaneous:    
      - Docker: DOCKER.md
      - License: license.md
      - Mkdocs: mkdocs.md
      - About: about.md
       
theme: readthedocs
