#!/bin/bash

Notes() {
	cat << EOF
https://www.calhoun.io/using-code-generation-to-survive-without-generics-in-go/
https://godoc.org/github.com/cznic/ebnf2y
EOF
}

go run gen/main.go -name=QString -type=string > qstring.go
go run gen/main.go -name=QInt -type=int > 		Qint.go
