/* SWGRAPH.C 
		  Generate Graphviz input 
		  
TODO: 
	. Everything  	  
*/
#include <stdio.h>
#include <stdlib.h>
#include "nemod.h"

#define P(s) printf("%s\n",(#s));
void genSuffix() {

	P(wg.Wait());
	printf("}\n");
}

void genPrefix(int nflows) {

	printf("#Prefix here. %d flows\n",nflows);
	P(*		 	 DO NOT EDIT!!!
 *		generated by sw 
**/);

	printf("\t}\n\n");
}
	
static void genProcs(Process p) {	
    
	while(p) {
			printf("#(%s %s.%s) %d ports\n",
				p->name, 			
				p->comp->path,
				p->comp->name,
				p->nportsIn + p->nportsOut
			);
			p=p->next;
	}	
	
	printf("\n");
}	



void genGraph(Model nemod) {
	Flow f;
	Process p;
	
	
				//* Generate Prefix code */
	genPrefix(nemod->nflows);
	
	if (!nemod) {
			fprintf(stderr,"swgo/FAIL: Missing model\n");
			exit(1);
	}
	
				
			//* Generate commented Reconstructed Network Definition */
	printf("#########   Expanded Network Definition   ######### \n");
	f=nemod->flow;

	while(f) {
			printf("# (%s %s.%s)%d <- %d(%s %s.%s) \n", 
				f->sink->name,
				f->sink->comp->path,
				f->sink->comp->name,
				f->sink_id, 
				f->source_id, 
				f->source->name,
				f->source->comp->path,
				f->source->comp->name
			);
				
		f=f->next;
	}
	
	printf("\n");		 
	p=nemod->proc;  /* Get first process */
	genProcs(p); 
	genSuffix();	//* Generate Suffix code */
}

/*    End of SWGRAPH.C  */
