/* File generated by the BNF Converter (bnfc 2.9.3). */

#ifndef PARSER_HEADER_FILE
#define PARSER_HEADER_FILE

#include <stdio.h>
#include "Absyn.h"

Valide  pValide(FILE *inp);
Valide psValide(const char *str);
ValidSW  pValidSW(FILE *inp);
ValidSW psValidSW(const char *str);
ValidConfig  pValidConfig(FILE *inp);
ValidConfig psValidConfig(const char *str);

#endif
