/* SWGO.C 
		  Greate StreamWork Go program 
*/
#include <stdio.h>
#include <stdlib.h>
#include "nemod.h"

void genGo(Model mod) {
	Flow f;
	
	//? genND(mod);
	
	fprintf(stderr,"GenGo: %d flows.\n", mod->nflows);
	
	if (!mod) {
			fprintf(stderr,"swgo/FAIL: Missing model\n");
			exit(1);
	}
	
				//* Generate Prefix code */
				
				//* Generate Flow code */
	f=mod->flow;
	while(f) {
			printf("/* (%s %s.%s)%d<-%d(%s %s.%s) */\n", 
				f->sink->name,
				f->sink->comp->path,
				f->sink->comp->name,
				f->sink->port->id, 
				f->source->port->id, 
				f->source->name,
				f->source->comp->path,
				f->source->comp->name
			);
				
		f=f->next;
	}
				//* Generate Suffix code */
}

/* Generate Expanded Network Definition */
void genND(Model mod) {
	Flow f;
	
	//fprintf(stderr,"GenGo: %d flows.\n", mod->nflows);
	
	if (!mod) {
			fprintf(stderr,"swgo/FAIL: Missing model\n");
			exit(1);
	}
	
				//* Generate Prefix code */
	printf("StreamWork Network Definition.  Generated by sw. \n");				
				
				//* Generate  Network Definition */
	f=mod->flow;
	while(f) {
		if ( f->sink->port->id )
			printf("(%s)%d<-%d(%s) \n", f->sink->name,f->sink->port->id, f->source->port->id, f->source->name);
		else 
			printf(" (%s)%d<-(%s) \n", f->sink->name, f->source->port->id, f->source->name);		
				
		f=f->next;
	}
				//* Generate Suffix code */
}

